"""Generate Vercel-format agent skills and update AGENTS.md.

For every converted or created CLI we emit:

    <skills_root>/<alias>/
        SKILL.md               # YAML frontmatter + agent instructions
        scripts/examples.sh    # runnable sample invocations
        references/tools.md    # full per-tool docs loaded on-demand

And we append (or update) a section in `AGENTS.md` at the repo root so any
agent that doesn't use the skill system still picks up the context.

Format reference: https://vercel.com/docs/agent-resources/skills
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


@dataclass
class ToolSpec:
    """Lightweight shape for skill rendering — decoupled from MCP types."""
    name: str
    description: str = ""
    input_schema: dict | None = None


def _yaml_escape(s: str) -> str:
    """Minimal YAML-safe escape for a single-line value."""
    s = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{s}"'


def render_skill_md(alias: str, description: str, tools: list[ToolSpec], binary: str | None = None) -> str:
    bin_name = binary or alias
    safe_desc = description.strip().replace("\n", " ")
    if not safe_desc:
        safe_desc = f"Use the {alias} CLI to interact with its MCP-backed tools."

    header = (
        "---\n"
        f"name: {alias}\n"
        f"description: {_yaml_escape(safe_desc)}\n"
        "license: MIT\n"
        "allowed-tools: Bash\n"
        "metadata:\n"
        f"  generator: cli-use\n"
        f"  tool_count: \"{len(tools)}\"\n"
        "---\n\n"
    )

    body: list[str] = []
    body.append(f"# {alias}")
    body.append("")
    body.append(
        f"You have access to the `{bin_name}` CLI, generated by **cli-use** "
        f"from an MCP server. Prefer this CLI over direct MCP tool-use — "
        f"it is dramatically cheaper in tokens (measured ~60-80% savings) and "
        f"composes with standard Unix pipes."
    )
    body.append("")
    body.append("## When to use")
    body.append("")
    body.append(f"Use `{bin_name}` whenever a task calls for: {safe_desc.lower()}")
    body.append("")

    if tools:
        body.append("## Quick reference")
        body.append("")
        body.append("```")
        width = max(len(t.name) for t in tools)
        for t in tools:
            first = (t.description or "").strip().split("\n", 1)[0]
            if len(first) > 70:
                first = first[:69] + "…"
            body.append(f"  {t.name:<{width}}  {first}")
        body.append("```")
        body.append("")

    body.append("## How to invoke")
    body.append("")
    body.append("```bash")
    body.append(f"{bin_name} --help                 # compact tool list")
    body.append(f"{bin_name} --list-tools           # JSON (machine-readable)")
    body.append(f"{bin_name} <tool> --help          # flags for a specific tool")
    body.append(f"{bin_name} <tool> --flag value    # invoke a tool")
    body.append("```")
    body.append("")
    body.append(
        "Output goes to stdout as plain text so it composes with `jq`, "
        "`grep`, `awk`. Errors go to stderr with a non-zero exit code."
    )
    body.append("")

    if tools:
        sample = tools[:3]
        body.append("## Examples")
        body.append("")
        body.append("```bash")
        for t in sample:
            args_hint = _sample_args_hint(t)
            body.append(f"{bin_name} {t.name}{args_hint}")
        body.append("```")
        body.append("")

    body.append("See `references/tools.md` for full argument schemas. See ")
    body.append("`scripts/examples.sh` for ready-to-run invocations.")
    body.append("")

    return header + "\n".join(body)


def _sample_args_hint(t: ToolSpec) -> str:
    schema = t.input_schema or {}
    required = schema.get("required", []) or []
    props = schema.get("properties", {}) or {}
    if not required:
        return ""
    parts: list[str] = []
    for r in required[:3]:
        prop = props.get(r, {})
        ptype = prop.get("type", "string")
        placeholder = "<json>" if ptype in {"object", "array"} else f"<{r}>"
        parts.append(f"--{r} {placeholder}")
    return " " + " ".join(parts)


def render_examples_sh(alias: str, tools: list[ToolSpec], binary: str | None = None) -> str:
    bin_name = binary or alias
    lines: list[str] = ["#!/usr/bin/env bash", f"# Sample invocations of the {alias} CLI.", "set -euo pipefail", ""]
    for t in tools[:10]:
        first = (t.description or "").strip().split("\n", 1)[0] or t.name
        args_hint = _sample_args_hint(t)
        lines.append(f"# {first}")
        lines.append(f"{bin_name} {t.name}{args_hint}")
        lines.append("")
    return "\n".join(lines)


def render_tools_md(alias: str, tools: list[ToolSpec]) -> str:
    lines = [f"# `{alias}` — full tool reference", ""]
    lines.append("Generated by cli-use. Load this only when you need detailed argument schemas.")
    lines.append("")
    for t in tools:
        lines.append(f"## `{t.name}`")
        lines.append("")
        if t.description:
            lines.append(t.description.strip())
            lines.append("")
        schema = t.input_schema or {}
        props = schema.get("properties", {}) or {}
        required = set(schema.get("required", []) or [])
        if props:
            lines.append("**Arguments:**")
            lines.append("")
            for pname, pschema in props.items():
                ptype = pschema.get("type", "any")
                desc = (pschema.get("description", "") or "").strip().replace("\n", " ")
                marker = "required" if pname in required else "optional"
                line = f"- `--{pname}` ({ptype}, {marker})"
                if desc:
                    line += f" — {desc}"
                lines.append(line)
            lines.append("")
    return "\n".join(lines)


def emit_skill(
    alias: str,
    description: str,
    tools: list[ToolSpec],
    skills_root: Path | str = "skills",
    binary: str | None = None,
) -> Path:
    """Write the skill directory. Returns the skill directory path."""
    out = Path(skills_root) / alias
    out.mkdir(parents=True, exist_ok=True)
    (out / "SKILL.md").write_text(render_skill_md(alias, description, tools, binary=binary), encoding="utf-8")
    scripts = out / "scripts"
    scripts.mkdir(exist_ok=True)
    (scripts / "examples.sh").write_text(render_examples_sh(alias, tools, binary=binary), encoding="utf-8")
    try:
        (scripts / "examples.sh").chmod(0o755)
    except Exception:
        pass
    refs = out / "references"
    refs.mkdir(exist_ok=True)
    (refs / "tools.md").write_text(render_tools_md(alias, tools), encoding="utf-8")
    return out


# ---- AGENTS.md ---------------------------------------------------------

_AGENTS_HEADER = (
    "# Agents\n\n"
    "This file provides persistent context to coding agents working in this repo.\n\n"
    "The following CLIs were installed by **cli-use**. Prefer them over raw MCP\n"
    "tool-use — they save tokens and compose with bash pipes.\n\n"
)


def update_agents_md(
    alias: str,
    description: str,
    tools: list[ToolSpec],
    binary: str | None = None,
    agents_path: Path | str = "AGENTS.md",
) -> Path:
    path = Path(agents_path)
    bin_name = binary or alias
    start = f"<!-- cli-use:{alias}:start -->"
    end = f"<!-- cli-use:{alias}:end -->"

    top_tools = ", ".join(f"`{t.name}`" for t in tools[:6]) if tools else ""
    section_lines = [
        start,
        f"## `{bin_name}` CLI",
        "",
        description.strip() or f"CLI for the {alias} MCP server.",
        "",
        f"{len(tools)} tools. Quick list: `{bin_name} --help`. Full schemas: `skills/{alias}/references/tools.md`.",
    ]
    if top_tools:
        section_lines.append("")
        section_lines.append(f"Top tools: {top_tools}.")
    section_lines.append(end)
    section = "\n".join(section_lines)

    if path.exists():
        content = path.read_text(encoding="utf-8")
        if start in content and end in content:
            pattern = re.escape(start) + r".*?" + re.escape(end)
            content = re.sub(pattern, section, content, flags=re.DOTALL)
        else:
            content = content.rstrip() + "\n\n" + section + "\n"
        path.write_text(content, encoding="utf-8")
    else:
        path.write_text(_AGENTS_HEADER + section + "\n", encoding="utf-8")
    return path
